# docker-compose.yml

version: "3"

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - ./backend:/musicians-project
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=guitar_db
    ports:
      - 27017:27017
    restart: always
