# Generated by Django 4.1.3 on 2022-11-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_blog_maker', models.CharField(blank=True, max_length=200, null=True)),
                ('name_of_musician', models.CharField(max_length=200)),
                ('name_of_band', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('appreciation', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(default=None, upload_to='media/')),
                ('music_1', models.FileField(default=None, upload_to='media/')),
                ('music_1_name', models.CharField(blank=True, max_length=200, null=True)),
                ('music_1_votes', models.IntegerField(default=0)),
                ('music_1_users', models.JSONField(default=dict)),
                ('music_2', models.FileField(default=None, upload_to='media/')),
                ('music_2_name', models.CharField(blank=True, max_length=200, null=True)),
                ('music_2_votes', models.IntegerField(default=0)),
                ('music_2_users', models.JSONField(default=dict)),
                ('music_3', models.FileField(default=None, upload_to='media/')),
                ('music_3_name', models.CharField(blank=True, max_length=200, null=True)),
                ('music_3_votes', models.IntegerField(default=0)),
                ('music_3_users', models.JSONField(default=dict)),
            ],
        ),
    ]
