name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

steps:
    
    # Docker Login
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker Image
      - name: Build the Docker image
        run: docker build https://github.com/Apro2011/Collaboration-Project/tree/develop/backend --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/Musicians-Paradise

    # Push docker image to Dockerhub
      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/Musicians-Paradise